/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Board = Array<Array<[] | [Piece]>>;
export type GameMode = { 'Bullet' : null } |
  { 'Online' : null } |
  { 'Blitz' : null } |
  { 'Correspondence' : null } |
  { 'Blindfold' : null } |
  { 'TimeControl' : { 'incrementSeconds' : bigint, 'baseSeconds' : bigint } } |
  { 'Rapid' : null } |
  { 'Standard' : null } |
  { 'FischerRandom' : null };
export type NotationType = { 'ShortAlgebraic' : null } |
  { 'AlgebraicCoordinate' : null } |
  { 'Descriptive' : string } |
  { 'LongAlgebraic' : null } |
  { 'Unknown' : string } |
  { 'International' : null };
export interface Piece {
  'kind' : PieceKind,
  'color' : PieceColor,
  'hasMoved' : boolean,
}
export type PieceColor = { 'Black' : null } |
  { 'White' : null };
export type PieceKind = { 'Bishop' : null } |
  { 'King' : null } |
  { 'Pawn' : null } |
  { 'Rook' : null } |
  { 'Knight' : null } |
  { 'Queen' : null };
export interface Position { 'x' : bigint, 'y' : bigint }
export interface RulesExplanation {
  'stalemate' : string,
  'touchMove' : string,
  'enPassant' : string,
  'pawnPromotion' : string,
  'check' : string,
  'turnTaking' : string,
  'tournamentFormat' : string,
  'checkmate' : string,
  'fiftyMoveRule' : string,
  'castle' : string,
  'basicMovement' : string,
  'timeControls' : string,
}
export interface _SERVICE {
  'determineChessNotationType' : ActorMethod<[string], NotationType>,
  'explainChessRules' : ActorMethod<[GameMode], RulesExplanation>,
  'explainEnPassant' : ActorMethod<[string], string>,
  'getLegalMoves' : ActorMethod<[Position], Array<Position>>,
  'getStartingPosition' : ActorMethod<[], Board>,
  'isPathClear' : ActorMethod<[PieceKind, Position, Position], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];