/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NotationType = IDL.Variant({
  'ShortAlgebraic' : IDL.Null,
  'AlgebraicCoordinate' : IDL.Null,
  'Descriptive' : IDL.Text,
  'LongAlgebraic' : IDL.Null,
  'Unknown' : IDL.Text,
  'International' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'Bullet' : IDL.Null,
  'Online' : IDL.Null,
  'Blitz' : IDL.Null,
  'Correspondence' : IDL.Null,
  'Blindfold' : IDL.Null,
  'TimeControl' : IDL.Record({
    'incrementSeconds' : IDL.Nat,
    'baseSeconds' : IDL.Nat,
  }),
  'Rapid' : IDL.Null,
  'Standard' : IDL.Null,
  'FischerRandom' : IDL.Null,
});
export const RulesExplanation = IDL.Record({
  'stalemate' : IDL.Text,
  'touchMove' : IDL.Text,
  'enPassant' : IDL.Text,
  'pawnPromotion' : IDL.Text,
  'check' : IDL.Text,
  'turnTaking' : IDL.Text,
  'tournamentFormat' : IDL.Text,
  'checkmate' : IDL.Text,
  'fiftyMoveRule' : IDL.Text,
  'castle' : IDL.Text,
  'basicMovement' : IDL.Text,
  'timeControls' : IDL.Text,
});
export const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const PieceKind = IDL.Variant({
  'Bishop' : IDL.Null,
  'King' : IDL.Null,
  'Pawn' : IDL.Null,
  'Rook' : IDL.Null,
  'Knight' : IDL.Null,
  'Queen' : IDL.Null,
});
export const PieceColor = IDL.Variant({
  'Black' : IDL.Null,
  'White' : IDL.Null,
});
export const Piece = IDL.Record({
  'kind' : PieceKind,
  'color' : PieceColor,
  'hasMoved' : IDL.Bool,
});
export const Board = IDL.Vec(IDL.Vec(IDL.Opt(Piece)));

export const idlService = IDL.Service({
  'determineChessNotationType' : IDL.Func(
      [IDL.Text],
      [NotationType],
      ['query'],
    ),
  'explainChessRules' : IDL.Func([GameMode], [RulesExplanation], ['query']),
  'explainEnPassant' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getLegalMoves' : IDL.Func([Position], [IDL.Vec(Position)], ['query']),
  'getStartingPosition' : IDL.Func([], [Board], ['query']),
  'isPathClear' : IDL.Func(
      [PieceKind, Position, Position],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NotationType = IDL.Variant({
    'ShortAlgebraic' : IDL.Null,
    'AlgebraicCoordinate' : IDL.Null,
    'Descriptive' : IDL.Text,
    'LongAlgebraic' : IDL.Null,
    'Unknown' : IDL.Text,
    'International' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'Bullet' : IDL.Null,
    'Online' : IDL.Null,
    'Blitz' : IDL.Null,
    'Correspondence' : IDL.Null,
    'Blindfold' : IDL.Null,
    'TimeControl' : IDL.Record({
      'incrementSeconds' : IDL.Nat,
      'baseSeconds' : IDL.Nat,
    }),
    'Rapid' : IDL.Null,
    'Standard' : IDL.Null,
    'FischerRandom' : IDL.Null,
  });
  const RulesExplanation = IDL.Record({
    'stalemate' : IDL.Text,
    'touchMove' : IDL.Text,
    'enPassant' : IDL.Text,
    'pawnPromotion' : IDL.Text,
    'check' : IDL.Text,
    'turnTaking' : IDL.Text,
    'tournamentFormat' : IDL.Text,
    'checkmate' : IDL.Text,
    'fiftyMoveRule' : IDL.Text,
    'castle' : IDL.Text,
    'basicMovement' : IDL.Text,
    'timeControls' : IDL.Text,
  });
  const Position = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const PieceKind = IDL.Variant({
    'Bishop' : IDL.Null,
    'King' : IDL.Null,
    'Pawn' : IDL.Null,
    'Rook' : IDL.Null,
    'Knight' : IDL.Null,
    'Queen' : IDL.Null,
  });
  const PieceColor = IDL.Variant({ 'Black' : IDL.Null, 'White' : IDL.Null });
  const Piece = IDL.Record({
    'kind' : PieceKind,
    'color' : PieceColor,
    'hasMoved' : IDL.Bool,
  });
  const Board = IDL.Vec(IDL.Vec(IDL.Opt(Piece)));
  
  return IDL.Service({
    'determineChessNotationType' : IDL.Func(
        [IDL.Text],
        [NotationType],
        ['query'],
      ),
    'explainChessRules' : IDL.Func([GameMode], [RulesExplanation], ['query']),
    'explainEnPassant' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getLegalMoves' : IDL.Func([Position], [IDL.Vec(Position)], ['query']),
    'getStartingPosition' : IDL.Func([], [Board], ['query']),
    'isPathClear' : IDL.Func(
        [PieceKind, Position, Position],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };