/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Board = Array<Array<Piece | null>>;
export interface Position {
    x: bigint;
    y: bigint;
}
export interface RulesExplanation {
    stalemate: string;
    touchMove: string;
    enPassant: string;
    pawnPromotion: string;
    check: string;
    turnTaking: string;
    tournamentFormat: string;
    checkmate: string;
    fiftyMoveRule: string;
    castle: string;
    basicMovement: string;
    timeControls: string;
}
export interface Piece {
    kind: PieceKind;
    color: PieceColor;
    hasMoved: boolean;
}
export type GameMode = {
    __kind__: "Bullet";
    Bullet: null;
} | {
    __kind__: "Online";
    Online: null;
} | {
    __kind__: "Blitz";
    Blitz: null;
} | {
    __kind__: "Correspondence";
    Correspondence: null;
} | {
    __kind__: "Blindfold";
    Blindfold: null;
} | {
    __kind__: "TimeControl";
    TimeControl: {
        incrementSeconds: bigint;
        baseSeconds: bigint;
    };
} | {
    __kind__: "Rapid";
    Rapid: null;
} | {
    __kind__: "Standard";
    Standard: null;
} | {
    __kind__: "FischerRandom";
    FischerRandom: null;
};
export type NotationType = {
    __kind__: "ShortAlgebraic";
    ShortAlgebraic: null;
} | {
    __kind__: "AlgebraicCoordinate";
    AlgebraicCoordinate: null;
} | {
    __kind__: "Descriptive";
    Descriptive: string;
} | {
    __kind__: "LongAlgebraic";
    LongAlgebraic: null;
} | {
    __kind__: "Unknown";
    Unknown: string;
} | {
    __kind__: "International";
    International: null;
};
export enum PieceColor {
    Black = "Black",
    White = "White"
}
export enum PieceKind {
    Bishop = "Bishop",
    King = "King",
    Pawn = "Pawn",
    Rook = "Rook",
    Knight = "Knight",
    Queen = "Queen"
}
export interface backendInterface {
    determineChessNotationType(notation: string): Promise<NotationType>;
    explainChessRules(_mode: GameMode): Promise<RulesExplanation>;
    explainEnPassant(_move: string): Promise<string>;
    getLegalMoves(_pos: Position): Promise<Array<Position>>;
    getStartingPosition(): Promise<Board>;
    isPathClear(_pieceKind: PieceKind, from: Position, to: Position): Promise<boolean>;
}
import type { Board as _Board, GameMode as _GameMode, NotationType as _NotationType, Piece as _Piece, PieceColor as _PieceColor, PieceKind as _PieceKind } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async determineChessNotationType(arg0: string): Promise<NotationType> {
        if (this.processError) {
            try {
                const result = await this.actor.determineChessNotationType(arg0);
                return from_candid_NotationType_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.determineChessNotationType(arg0);
            return from_candid_NotationType_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async explainChessRules(arg0: GameMode): Promise<RulesExplanation> {
        if (this.processError) {
            try {
                const result = await this.actor.explainChessRules(to_candid_GameMode_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.explainChessRules(to_candid_GameMode_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async explainEnPassant(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.explainEnPassant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.explainEnPassant(arg0);
            return result;
        }
    }
    async getLegalMoves(arg0: Position): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalMoves(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalMoves(arg0);
            return result;
        }
    }
    async getStartingPosition(): Promise<Board> {
        if (this.processError) {
            try {
                const result = await this.actor.getStartingPosition();
                return from_candid_Board_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStartingPosition();
            return from_candid_Board_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isPathClear(arg0: PieceKind, arg1: Position, arg2: Position): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPathClear(to_candid_PieceKind_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPathClear(to_candid_PieceKind_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
}
function from_candid_Board_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Board): Board {
    return from_candid_vec_n6(_uploadFile, _downloadFile, value);
}
function from_candid_NotationType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotationType): NotationType {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_PieceColor_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PieceColor): PieceColor {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PieceKind_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PieceKind): PieceKind {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Piece_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Piece): Piece {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Piece]): Piece | null {
    return value.length === 0 ? null : from_candid_Piece_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kind: _PieceKind;
    color: _PieceColor;
    hasMoved: boolean;
}): {
    kind: PieceKind;
    color: PieceColor;
    hasMoved: boolean;
} {
    return {
        kind: from_candid_PieceKind_n11(_uploadFile, _downloadFile, value.kind),
        color: from_candid_PieceColor_n13(_uploadFile, _downloadFile, value.color),
        hasMoved: value.hasMoved
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bishop: null;
} | {
    King: null;
} | {
    Pawn: null;
} | {
    Rook: null;
} | {
    Knight: null;
} | {
    Queen: null;
}): PieceKind {
    return "Bishop" in value ? PieceKind.Bishop : "King" in value ? PieceKind.King : "Pawn" in value ? PieceKind.Pawn : "Rook" in value ? PieceKind.Rook : "Knight" in value ? PieceKind.Knight : "Queen" in value ? PieceKind.Queen : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Black: null;
} | {
    White: null;
}): PieceColor {
    return "Black" in value ? PieceColor.Black : "White" in value ? PieceColor.White : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ShortAlgebraic: null;
} | {
    AlgebraicCoordinate: null;
} | {
    Descriptive: string;
} | {
    LongAlgebraic: null;
} | {
    Unknown: string;
} | {
    International: null;
}): {
    __kind__: "ShortAlgebraic";
    ShortAlgebraic: null;
} | {
    __kind__: "AlgebraicCoordinate";
    AlgebraicCoordinate: null;
} | {
    __kind__: "Descriptive";
    Descriptive: string;
} | {
    __kind__: "LongAlgebraic";
    LongAlgebraic: null;
} | {
    __kind__: "Unknown";
    Unknown: string;
} | {
    __kind__: "International";
    International: null;
} {
    return "ShortAlgebraic" in value ? {
        __kind__: "ShortAlgebraic",
        ShortAlgebraic: value.ShortAlgebraic
    } : "AlgebraicCoordinate" in value ? {
        __kind__: "AlgebraicCoordinate",
        AlgebraicCoordinate: value.AlgebraicCoordinate
    } : "Descriptive" in value ? {
        __kind__: "Descriptive",
        Descriptive: value.Descriptive
    } : "LongAlgebraic" in value ? {
        __kind__: "LongAlgebraic",
        LongAlgebraic: value.LongAlgebraic
    } : "Unknown" in value ? {
        __kind__: "Unknown",
        Unknown: value.Unknown
    } : "International" in value ? {
        __kind__: "International",
        International: value.International
    } : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<[] | [_Piece]>>): Array<Array<Piece | null>> {
    return value.map((x)=>from_candid_vec_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_Piece]>): Array<Piece | null> {
    return value.map((x)=>from_candid_opt_n8(_uploadFile, _downloadFile, x));
}
function to_candid_GameMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PieceKind_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PieceKind): _PieceKind {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PieceKind): {
    Bishop: null;
} | {
    King: null;
} | {
    Pawn: null;
} | {
    Rook: null;
} | {
    Knight: null;
} | {
    Queen: null;
} {
    return value == PieceKind.Bishop ? {
        Bishop: null
    } : value == PieceKind.King ? {
        King: null
    } : value == PieceKind.Pawn ? {
        Pawn: null
    } : value == PieceKind.Rook ? {
        Rook: null
    } : value == PieceKind.Knight ? {
        Knight: null
    } : value == PieceKind.Queen ? {
        Queen: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Bullet";
    Bullet: null;
} | {
    __kind__: "Online";
    Online: null;
} | {
    __kind__: "Blitz";
    Blitz: null;
} | {
    __kind__: "Correspondence";
    Correspondence: null;
} | {
    __kind__: "Blindfold";
    Blindfold: null;
} | {
    __kind__: "TimeControl";
    TimeControl: {
        incrementSeconds: bigint;
        baseSeconds: bigint;
    };
} | {
    __kind__: "Rapid";
    Rapid: null;
} | {
    __kind__: "Standard";
    Standard: null;
} | {
    __kind__: "FischerRandom";
    FischerRandom: null;
}): {
    Bullet: null;
} | {
    Online: null;
} | {
    Blitz: null;
} | {
    Correspondence: null;
} | {
    Blindfold: null;
} | {
    TimeControl: {
        incrementSeconds: bigint;
        baseSeconds: bigint;
    };
} | {
    Rapid: null;
} | {
    Standard: null;
} | {
    FischerRandom: null;
} {
    return value.__kind__ === "Bullet" ? {
        Bullet: value.Bullet
    } : value.__kind__ === "Online" ? {
        Online: value.Online
    } : value.__kind__ === "Blitz" ? {
        Blitz: value.Blitz
    } : value.__kind__ === "Correspondence" ? {
        Correspondence: value.Correspondence
    } : value.__kind__ === "Blindfold" ? {
        Blindfold: value.Blindfold
    } : value.__kind__ === "TimeControl" ? {
        TimeControl: value.TimeControl
    } : value.__kind__ === "Rapid" ? {
        Rapid: value.Rapid
    } : value.__kind__ === "Standard" ? {
        Standard: value.Standard
    } : value.__kind__ === "FischerRandom" ? {
        FischerRandom: value.FischerRandom
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
